groups:
  - name: deep-echo-alerts
    rules:
      # Application health alerts
      - alert: DeepEchoServiceDown
        expr: up{job=~"deep-echo-.*"} == 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Deep Echo service {{ $labels.job }} is down"
          description: "Deep Echo service {{ $labels.job }} has been down for more than 2 minutes."

      - alert: HighErrorRate
        expr: rate(flask_http_request_exceptions_total[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High error rate in Deep Echo application"
          description: "Error rate is {{ $value }} errors per second over the last 5 minutes."

      # Performance alerts
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(flask_http_request_duration_seconds_bucket[5m])) > 1.0
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High response time in Deep Echo application"
          description: "95th percentile response time is {{ $value }}s over the last 10 minutes."

      - alert: HighCPUUsage
        expr: (100 - (avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)) > 80
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage"
          description: "CPU usage is above 80% for more than 10 minutes on {{ $labels.instance }}"

      - alert: HighMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 80
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage"
          description: "Memory usage is above 80% for more than 10 minutes on {{ $labels.instance }}"

      # Cache alerts
      - alert: LowCacheHitRate
        expr: (increase(cache_hits_total[5m]) / increase(cache_requests_total[5m])) * 100 < 50
        for: 15m
        labels:
          severity: warning
        annotations:
          summary: "Low cache hit rate"
          description: "Cache hit rate is {{ $value }}% over the last 15 minutes."

      - alert: RedisDown
        expr: up{job="redis"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Redis is down"
          description: "Redis has been down for more than 1 minute."

      # Load balancer alerts
      - alert: LoadBalancerUnhealthy
        expr: healthy_backends / total_backends < 0.5
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Load balancer has too few healthy backends"
          description: "Less than 50% of backends are healthy for more than 5 minutes."

      # Cognitive processing alerts
      - alert: HighCognitiveProcessingTime
        expr: histogram_quantile(0.95, rate(cognitive_processing_duration_seconds_bucket[5m])) > 5.0
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High cognitive processing time"
          description: "95th percentile cognitive processing time is {{ $value }}s over the last 10 minutes."

      - alert: CognitiveServiceOverloaded
        expr: cognitive_active_sessions > cognitive_max_sessions * 0.9
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Cognitive service is overloaded"
          description: "Cognitive service has {{ $value }} active sessions, approaching the limit."

  - name: deep-echo-infrastructure
    rules:
      # Disk space alerts
      - alert: DiskSpaceLow
        expr: (node_filesystem_avail_bytes / node_filesystem_size_bytes) * 100 < 20
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Disk space is low"
          description: "Disk space is below 20% on {{ $labels.instance }} ({{ $labels.mountpoint }})"

      - alert: DiskSpaceCritical
        expr: (node_filesystem_avail_bytes / node_filesystem_size_bytes) * 100 < 10
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Disk space is critically low"
          description: "Disk space is below 10% on {{ $labels.instance }} ({{ $labels.mountpoint }})"

      # Database alerts
      - alert: DatabaseConnectionsHigh
        expr: pg_stat_database_numbackends / pg_settings_max_connections * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Database connections are high"
          description: "Database connections are above 80% of the maximum."

      # Container alerts
      - alert: ContainerKilled
        expr: increase(container_killed_total[1m]) > 0
        for: 0m
        labels:
          severity: warning
        annotations:
          summary: "Container was killed"
          description: "Container {{ $labels.name }} was killed."

      - alert: ContainerCPUThrottled
        expr: rate(container_cpu_cfs_throttled_seconds_total[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Container CPU is being throttled"
          description: "Container {{ $labels.name }} is being CPU throttled."