apiVersion: apps/v1
kind: Deployment
metadata:
  name: deep-echo-cognitive
  labels:
    app: deep-echo-cognitive
    component: microservice
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  selector:
    matchLabels:
      app: deep-echo-cognitive
  template:
    metadata:
      labels:
        app: deep-echo-cognitive
        component: microservice
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8001"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: deep-echo-microservice
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: cognitive-service
        image: ghcr.io/echocog/deep-tree-echo-rkwv-microservice:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8001
          name: http
          protocol: TCP
        env:
        - name: COGNITIVE_SERVICE_PORT
          value: "8001"
        - name: MAX_CONCURRENT_SESSIONS
          value: "50"
        - name: ENABLE_CACHING
          value: "true"
        - name: CACHE_TTL_SECONDS
          value: "300"
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: deep-echo-secrets
              key: redis-url
        - name: SERVICE_REGISTRY_URL
          value: "http://deep-echo-lb:8000"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: temp-storage
          mountPath: /app/temp
      volumes:
      - name: temp-storage
        emptyDir: {}
      nodeSelector:
        kubernetes.io/arch: amd64
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - deep-echo-cognitive
              topologyKey: kubernetes.io/hostname

---
apiVersion: v1
kind: Service
metadata:
  name: deep-echo-cognitive
  labels:
    app: deep-echo-cognitive
    component: microservice
spec:
  type: ClusterIP
  ports:
  - port: 8001
    targetPort: 8001
    protocol: TCP
    name: http
  selector:
    app: deep-echo-cognitive

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: deep-echo-cognitive-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deep-echo-cognitive
  minReplicas: 3
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15