apiVersion: v2
name: deep-echo
description: A Helm chart for Deep Tree Echo WebVM-RWKV cognitive architecture
type: application
version: 0.1.0
appVersion: "1.1.0"

keywords:
  - cognitive-architecture
  - ai
  - rwkv
  - microservices

home: https://github.com/EchoCog/deep-tree-echo-rkwv
sources:
  - https://github.com/EchoCog/deep-tree-echo-rkwv

maintainers:
  - name: Deep Echo Team
    email: team@deepecho.ai

dependencies:
  - name: redis
    version: "17.15.6"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  - name: postgresql
    version: "12.12.10"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: prometheus
    version: "25.8.0"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: monitoring.prometheus.enabled
  - name: grafana
    version: "7.0.19"
    repository: "https://grafana.github.io/helm-charts"
    condition: monitoring.grafana.enabled